---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 61e1f3a49697b38c7a23460822c5f454f803f5d8
    app.quarkus.io/build-timestamp: 2021-09-06 - 12:35:16 +0000
  labels:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: webinar-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 61e1f3a49697b38c7a23460822c5f454f803f5d8
    app.quarkus.io/build-timestamp: 2021-09-06 - 12:35:16 +0000
  labels:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: webinar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webinar-demo
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 61e1f3a49697b38c7a23460822c5f454f803f5d8
        app.quarkus.io/build-timestamp: 2021-09-06 - 12:35:16 +0000
      labels:
        app.kubernetes.io/name: webinar-demo
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
            - name: JAVA_OPTIONS
              value: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
          image: user_opensh/webinar-demo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: webinar-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
