---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 5c5f7347bec5df87cda87f0d33eff5004938cf31
    app.quarkus.io/build-timestamp: 2021-10-06 - 09:08:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0
  name: quarkus-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 5c5f7347bec5df87cda87f0d33eff5004938cf31
    app.quarkus.io/build-timestamp: 2021-10-06 - 09:08:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0
  name: quarkus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-demo
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 5c5f7347bec5df87cda87f0d33eff5004938cf31
        app.quarkus.io/build-timestamp: 2021-10-06 - 09:08:20 +0000
      labels:
        app.kubernetes.io/name: quarkus-demo
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
            - name: JAVA_OPTIONS
              value: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
          image: user_opensh/quarkus-demo:1.0.0
          imagePullPolicy: Always
          name: quarkus-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 5c5f7347bec5df87cda87f0d33eff5004938cf31
    app.quarkus.io/build-timestamp: 2021-10-06 - 09:08:20 +0000
  labels:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0
  name: quarkus-demo
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: quarkus-demo
                port:
                  name: http
            path: /
            pathType: Prefix
