---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: webinar-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: webinar-demo
  name: webinar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: webinar-demo
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
        app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: webinar-demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: admin/webinar-demo:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: webinar-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
