---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: webinar-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi-quarkus-native-binary-s2i
spec:
  dockerImageRepository: quay.io/quarkus/ubi-quarkus-native-binary-s2i
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: webinar-demo
    app.openshift.io/runtime: quarkus
  name: webinar-demo
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: webinar-demo
    app.openshift.io/runtime: quarkus
  name: webinar-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: webinar-demo:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi-quarkus-native-binary-s2i:1.0
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: webinar-demo
    app.openshift.io/runtime: quarkus
  name: webinar-demo
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
        app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: webinar-demo
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_HOME
              value: /home/quarkus/
            - name: QUARKUS_OPTS
              value: -Dquarkus.http.host=0.0.0.0
          image: admin/webinar-demo:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: webinar-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - webinar-demo
        from:
          kind: ImageStreamTag
          name: webinar-demo:1.0.0-SNAPSHOT
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 067ea629f8021336c86f2ce97de350f15ff543d1
    app.quarkus.io/build-timestamp: 2021-09-06 - 13:42:58 +0000
  labels:
    app.kubernetes.io/name: webinar-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: webinar-demo
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: webinar-demo
